### ISSUE TITLE
Problems that do not support password autocomplete in web browsers

### ISSUE THREAD

**Issue by blissray** [lablup/backend.ai-console#613]
![image](https://user-images.githubusercontent.com/8847089/87891393-c5192d00-ca74-11ea-8479-eafa89e3137d.png)

Typically, most web applications support automatic password completion. However, the backend.ai console does not support this feature. Do you have plans to add the feature?

**Comment by inureyes** [comment]
It is implemented but disabled to support API-IAM login. 

https://github.com/lablup/backend.ai-console/issues/480
https://github.com/lablup/backend.ai-console/issues/549

We will disable IAM login and support autocomplete for modern browsers since next release. (planned to today/tomorrow). Thank you and stay tuned :)

**Comment by blissray** [comment]
Thank you for your answer!

**Comment by inureyes** [comment]
@blissray v20.07.6 is released and cloud is also updated.
